version: '2.0'

services:
  bebeto:
    build: .
    container_name: bebeto
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - /gopamoja/images:/gopamoja/images
      - /gopamoja/baresi/dist/console:/gopamoja/baresi/dist/console
    ports:
      - 80:80
      - 443:443
    networks:
      - gopamoja

networks:
  gopamoja:
    external: true
